### ISSUE TITLE
Mirror: Colorizer must be enabled to have the Highlighter

### ISSUE THREAD

**Issue by elundmark** [elundmark/tz-aio-userscript#14]
Mirror: [openuserjs.org/scripts/elundmark/Torrentz_All-in-One/issues/Slight_Bug](https://openuserjs.org/scripts/elundmark/Torrentz_All-in-One/issues/Slight_Bug)
Author: [vitae](https://openuserjs.org/users/vitae) via [openuserjs.org](https://openuserjs.org/)

Loving this, but the one and only bug I see is that to have the Highlighter working, you must have the Colorizer enabled.
All those colors annoy me and when I disabled it, nearly the entire Highlight section on the Torrents disappeared with it and when reenabled were reset.

1. How I have it with Colorizer and Highlighter working
	- ![How I have it with Colorizer and Highlighter working](http://files.elundmark.se/images/tz-aio-issues/1_14_1c83fxL.png)
2. Now I disable Colorizer
	- ![Now I disable Colorizer](http://files.elundmark.se/images/tz-aio-issues/2_14_li1GMA6.png)
3. What I see now
	- ![What I see now](http://files.elundmark.se/images/tz-aio-issues/3_14_Wgye9Ga.png)
4. What I see now
	- ![What I see now](http://files.elundmark.se/images/tz-aio-issues/4_14_CCScv8y.png)
5. After reenabling Colorizer
	- ![After reenabling Colorizer](http://files.elundmark.se/images/tz-aio-issues/5_14_WTJzf6k.png)

The ones that are there after disabling Colorizer are the "any" ones.
A working solution to this bug is to just have whatever you want under the "any" setting:
any|1080p,720p,WebRip,WebDL,DVDScr
But you will have to reenable them to get them to display.

Other than that, loving this!
Would love it to work for KickAss and PirateBay (when it comes back)

**Comment by elundmark** [comment]
[Re](https://openuserjs.org/scripts/elundmark/Torrentz_All-in-One/issues/Slight_Bug#comment-14b30debc88): [@vitae](/users/vitae):   
Issue recieved :-/ I added this issue to the main [issue tracker #14](https://github.com/elundmark/tz-aio-userscript/issues/14) as well.

I can't duplicate that behaviour on my end using the latest version (**2.8.3**). I looked through the [changelog](https://github.com/elundmark/tz-aio-userscript/blob/master/Changelog.md) cuz I was sure I had noticed this problem earlier and fixed it, but apparently I must have fixed it without writing it down.

It should work, but if you really have the latest version installed, could you follow these steps and report back the results?

1. Export your settings (if you can).
2. Uninstall it completely (including all the settings **\*)**)and re-install w/ **v2.8.3**.
3. Try and duplicate the errors (Don't import your old settings yet!).
4. If you still see the issue, import your old settings and see if that makes any difference.

**\*)** IE GreaseMonkey lets you keep the settings when uninstalling, make sure that is turned off when you install, so you get a totally fresh install w/ the new version.

Still an issue?
Thanks!

**Comment by elundmark** [comment]
[Re](https://openuserjs.org/scripts/elundmark/Torrentz_All-in-One/issues/Slight_Bug#comment-14b30debc88): [@vitae](/users/vitae):   

I just realized, the images suggest that the issue may have something to do with the CSS. If you know how, could you try and manually replace the installed one with this (current) css file?
[http://elundmark.se/_files/js/tz-aio/tz-aio-style-2.css](http://elundmark.se/_files/js/tz-aio/tz-aio-style-2.css)

Something could have happened during an earlier upgrade, that didn't download the new file correctly...

_The easiest way in Firefox is to open the right folder with **Addons Manager > User Scripts > Torrentz All-in-One 2.8.3** (right-click -> Show containing folder), then replace `tz-aio-style-2.css` with the css file you downloaded from my site..._

**Comment by elundmark** [comment]
[Re](https://openuserjs.org/scripts/elundmark/Torrentz_All-in-One/issues/Slight_Bug#comment-14b30debc88): [@vitae](/users/vitae):   

Ok I found the culprit, very small fix but it could take an hour or so before a new version is online. Update later today, or keep an eye on [https://github.com/elundmark/tz-aio-userscript/releases](https://github.com/elundmark/tz-aio-userscript/releases).

I'll leave this issue open for now :-)

**Comment by elundmark** [comment]
Fixed, leaving this open for now.

**Comment by Martii** [comment]
**Side note**: I apologize in advance for being administrative interuptus again ... but please be careful when you mirror `Re: @vitae` from OUJS to GH... may not be the same user here on GH. Wouldn't want to have the wrong person notified here on GH. Thanks and peace out. :)

**Comment by elundmark** [comment]
Oops, didn't notice that, thanks!
