### ISSUE TITLE
New domain bestdownload.eu & Security Notice

### ISSUE THREAD

**Issue by AlienHeads** [elundmark/tz-aio-userscript#15]
The domain name changing not really an issue as i added the new domain to the includes.

The security notice interferes with the copy paste of torrent titles.
![screenshot-www bestdownload eu 2015-02-13 11-02-34](https://cloud.githubusercontent.com/assets/2960519/6186374/5e33bc66-b370-11e4-8915-42de7c31d557.png)

**Comment by elundmark** [comment]
Sorry 'been afk a lot, I'll fix those things within a few days, thanks!

**Comment by AlienHeads** [comment]
No problem, thank you this script is superb.

**Comment by elundmark** [comment]
Back from 6 days with the flu, itching to write some code now so expect an update today! :-)

**Comment by elundmark** [comment]
You wouldn't happen to have any saved html code for the ad? They've removed it...

**Comment by elundmark** [comment]
Couldn't find the ad, I'll do a separate update if/when I find it. Leaving this issue open.
Thanks!

**Comment by AlienHeads** [comment]
It's still showing at my end.
http://freetexthost.com/pffcqhk0tq

**Comment by elundmark** [comment]
Just caught it myself, copied the code too. I'll do the update tomorrow night, thanks for the code though :-)

**Comment by elundmark** [comment]
Comp died, all I have is a shatty $50 android phone. Getting a new laptop next week, back in action by next Friday :-)
